### ISSUE TITLE
Request for Contact Information for ARX Arm Procurement

### ISSUE THREAD

**Issue by prakharg01** [real-stanford/arx5-sdk#16]
Hi @yifan-hou @yihuai-gao,

We're interested in purchasing ARX arms but have been unable to get in touch with anyone from the company. If possible, could you help us connect with a representative or provide any contact information?

Thank you very much for your assistance!
(prakhs00@gmail.com)

Best regards,

**Comment by yifan-hou** [comment]
I forwarded your msg to ARX, they said they will contact you directly.

**Comment by yihuai-gao** [comment]
Please go to their [offical github account](https://github.com/ARXroboticsX) for more information. Their email is contact@arx-x.com
