### ISSUE TITLE
Mesh for ARX_L5

### ISSUE THREAD

**Issue by Sashare** [real-stanford/arx5-sdk#17]
https://github.com/real-stanford/arx5-sdk/blob/cc684e1e6148a8a616240694c48ab369ebcf88bf/models/L5.urdf#L21C38-L21C40

Dear @real-stanford team, hello!       
@yifan-hou  @huy-ha @yihuai-gao

My team is using nowadays robot with master manipulators ARX_L5. We have spent long time with trying to find .mesh files for URDF model L5.urdf :
https://github.com/real-stanford/arx5-sdk/blob/yihuai/models/L5.urdf
There are links for that in .urdf file: _**<mesh filename="package://meshes/L5/base_link.STL"/>**_
but we can't find _package://meshes/L5._
Could you be so kind to give us access to .mesh files?

**Comment by Sashare** [comment]
![Screenshot from 2024-12-02 11-14-14](https://github.com/user-attachments/assets/1b75fa5c-7dac-4bb4-ac37-199df7a67c65)
Dear @huy-ha 
thank you for your fast reply!

Could you tell me, is it okay that X5 and L5 urdf models looks kinda same?

**Comment by huy-ha** [comment]
I could be wrong, but I think kinematically the X5/L5 arms should be identical. The ARX folks made a lot of changes to the hardware during as well as after UMI on Legs, so we don't know what the latest version of the arm actually looks like. You can reach out to them to get the correct CAD model for your version.
